spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8083/realms/external/protocol/openid-connect/certs}
        external:
          introspection-uri: ${INTROSPECT_URI:http://localhost:8083/realms/external/protocol/openid-connect/token/introspect}
          introspection-client-id: ${INTROSPECT_ID:external-client-auth}
          introspection-client-secret: ${INTROSPECT_SECRET:TQOLOxZfm9IbHchYuZCH2yVGulrJ5X9W}
jwt:
  auth:
    converter:
      resource-id: my-super-client
      principal-attribute: principal_username
